# This cmake script builds local sbml.
include(ExternalProject)
MESSAGE("+++ Building local sbml")
SET(LIBSBML_SRC_DIR ${PROJECT_SOURCE_DIR}/dependencies/libsbml-5.11.3)
SET(SBML_INSTALL_DIR ${CMAKE_BINARY_DIR}/_libsbml)
FILE(MAKE_DIRECTORY ${SBML_INSTALL_DIR})

ADD_CUSTOM_COMMAND(OUTPUT _libsbml.out
    COMMAND ${CMAKE_COMMAND} -DCMAKE_INSTALL_PREFIX=${SBML_INSTALL_DIR}
    -DBUILD_SHARED_LIBS=OFF
    -DWITH_BZIP2=ON
    -DWITH_LIBXML=ON ${SBML_SRC_DIR}
    COMMAND make install
    WORKING_DIRECTORY ${SBML_INSTALL_DIR}
    VERBATIM
    )
    
ADD_CUSTOM_TARGET(_libsml ALL DEPENDS _libsbml.out)
MESSAGE("+++ LIBSBML_LIBRARY: ${LIBSBML_LIBRARY}")
set(LIBSBML_LIBRARY ${SBML_INSTALL_DIR}/lib/libsbml-static.a) 
include_directories(${SBML_INSTALL_DIR}/include)
